package it.mikyll.cluedo.model.networking;

public enum ActionGame {
	READY, PLAYER_TURN, CHARACTER_SELECTION, PLAYERS_LIST, CLUES_LIST, ACTION_MOVE, ACTION_ACCUSATION, ACTION_FINAL_ACCUSATION, ACTION_END_TURN
}
